# user api lists

### get
GET  http://localhost:8000/api/v1/user

###  create an User
POST http://localhost:8000/api/v1/user
Content-Type: application/json

{
    "fname" : "rupesh",
    "lname" : "Adhikari",
    "dob" : "2000-02-20", 
    "email" : "ee3h@a.com", 
    "password": "password",
    "phone": "040000000", 
    "address": "kent street, Belmore",
    "gender": "male" 
}
###  update User
PUT  http://localhost:8000/api/v1/user
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVlM2hAYS5jb20iLCJpYXQiOjE2MzM5MDE4MDQsImV4cCI6MTYzMzkwMjcwNH0.P0awX1cm2DcoTymxAQQouxO8lp_sYwq-SApgeY_Nb-s

{
    "fname" : "ruupesh",
    "lname" : "Adhikari",
    "dob" : "2000-02-20", 
    "email" : "ee3h@a.com", 
    
    "phone": "040000000", 
    "address": "kent street, Belmore",
    "gender": "male" 
}

###email verification api

POST http://localhost:8000/api/v1/user/email-verification
Content-Type: application/json

{
    "otp" :"98542773",
    "email":"ee213h@a.com"
}



# ######### category api lists
###  create new category

POST http://localhost:8000/api/v1/category
Content-Type: application/json

{
    "name": "the Grocery ",
    "parentCat": null 

}

### fetch category / new category

GET http://localhost:8000/api/v1/category
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVlM2hAYS5jb20iLCJpYXQiOjE2MzM0MDIxNDEsImV4cCI6MTYzMzQwMzA0MX0.Whmq05WfdPblScD6bvnmBREoGnLHcfxzpqjcYzLMncw

### delete categoty

DELETE http://localhost:8000/api/v1/category/61510470e8b7c07987b3bef9


###update edit category

PATCH  http://localhost:8000/api/v1/category
Content-Type: application/json

{
    "_id": "61525a69957c958f5de0d9a6",
    "name": "Goldstar plus plus ",
    "parentCat": "" 

}

###login

POST  http://localhost:8000/api/v1/user/login
Content-Type: application/json

{
    "email" : "ee3h@a.com",
    "password": "password"
}

### tokens API
###request for a new acceccJWT

GET  http://localhost:8000/api/v1/token
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVlM2hAYS5jb20iLCJpYXQiOjE2MzMzODg1MDcsImV4cCI6MTYzNTk4MDUwN30.zd72dgTC3_SwRfi7UOmy71zTXzIcyOSrWVmlbHgI4QM

### Payment option API list

### Get Payment options

GET  http://localhost:8000/api/v1/payment-option

### POST Payment options

POST  http://localhost:8000/api/v1/payment-option
Content-Type: application/json

{
    "status":false,
    "name":"Pay by Credit CArd",
    "info": "Hello hello"
}

###Delete payment

DELETE http://localhost:8000/api/v1/payment-option/616f6fb05af625c21d8dc1aa