# user api lists

### get
GET  http://localhost:8000/api/v1/user

###  create an User
POST http://localhost:8000/api/v1/user
Content-Type: application/json

{
    "fname" : "rupesh",
    "lname" : "Adhikari",
    "dob" : "2000-02-20", 
    "email" : "ee3h@a.com", 
    "password": "password",
    "phone": "040000000", 
    "address": "kent street, Belmore",
    "gender": "male" 
}

###email verification api

POST http://localhost:8000/api/v1/user/email-verification
Content-Type: application/json

{
    "otp" :"98542773",
    "email":"ee213h@a.com"
}



# ######### category api lists
###  create new category

POST http://localhost:8000/api/v1/category
Content-Type: application/json

{
    "name": "the Grocery ",
    "parentCat": null 

}

### fetch category / new category

GET http://localhost:8000/api/v1/category

### delete categoty

DELETE http://localhost:8000/api/v1/category/61510470e8b7c07987b3bef9

#update edit category
